enum TypeKeys {
  ERROR_SET = 'ERROR_SET',
  ERROR_CLEAR = 'ERROR_CLEAR',
  GIFS_CLEAR = 'GIFS_CLEAR',
  GIFS_TRENDING = 'GIFS_TRENDING',
  GIFS_SEARCH = 'GIFS_SEARCH',
  GIFS_SET = 'GIFS_SET',
  OTHER_ACTION = '__any_other_action_type__',
  SEARCH_ADD = 'SEARCH_ADD',
  SEARCH_CLEAR = 'SEARCH_CLEAR',
  SEARCH_REMOVE = 'SEARCH_REMOVE',
}

export default TypeKeys;
