enum TypeKeys {
  FETCHING = 'FETCHING',
  GIFS_CLEAR = 'GIFS_CLEAR',
  GIFS_TRENDING = 'GIFS_TRENDING',
  GIFS_SEARCH = 'GIFS_SEARCH',
  GIFS_SET = 'GIFS_SET',
  OTHER_ACTION = '__any_other_action_type__',
  PAGINATION_CLEAR = 'PAGINATION_CLEAR',
  PAGINATION_SET = 'PAGINATION_SET',
}

export default TypeKeys;
